      </div>
      <div class="push"><!--//--></div>
    </div>
    <footer class="navbar-inner">
      <span>2015. <a href="http://www.agu.org/">American Geophysical Union</a> | All Rights Reserved | Created by <a href="http://www.linkedin.com/pub/eric-rozell/22/638/48b/">Eric Rozell</a> and <a href="http://narock.github.io">Tom Narock</a> | Powered by <a href="http://lodspeakr.org/">LODSPeaKr</a></span>
    </footer>
  </body>
</html>
