<h6 style="font-size:.7em;">Created by <a href="http://www.linkedin.com/pub/eric-rozell/22/638/48b/">Eric Rozell</a> and <a href="http://userpages.umbc.edu/~tnarock/">Tom Narock</a> | Powered by <a href="http://lodspkr.org">LODSPeaKr</a></h6>
</div> <!-- end column -->
</div> <!-- end row -->
<!-- Container End -->
<footer >
	<div class="row">
	     <div class="columns small-12">
	     	  		 <hr />
				     </div>
				     </div>
				     <div class="row" role="contentinfo">

				     	  <div class="small-12 large-3 columns">
					       		       <article id="nav_menu-5" class="row widget widget_nav_menu"><div class="small-12 columns"><h6><strong>I Want To</strong></h6><div class="menu-footer-i-want-to-container"><ul id="menu-footer-i-want-to-1" class="menu"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2193"><a href="https://membership.agu.org/join-renew/">Join AGU</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2357"><a href="https://membership.agu.org/join-renew/">Renew AGU Membership</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2194"><a href="http://giving.agu.org/">Donate to AGU</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2197"><a href="http://onlinelibrary.wiley.com/agu/search/easi">Search Publications</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2195"><a href="http://meetings.agu.org/">Find an AGU Meeting</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2196"><a href="http://sites.agu.org/careers/">Visit the Career Center</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2198"><a href="http://ethics.agu.org/">Learn about AGU Scientific Integrity and Professional Ethics</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2199"><a href="http://about.agu.org/contact/">Contact AGU</a></li>
</ul></div></div></article>		   			   </div>

									<div class="small-12 large-5 columns">
									     		     <article id="nav_menu-6" class="row widget widget_nav_menu"><div class="small-12 columns"><h6><strong>Popular Links</strong></h6><div class="menu-footer-popular-links-container"><ul id="menu-footer-popular-links-1" class="menu"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2358"><a href="http://sites.agu.org/leadership/sections-focus-groups/">Sections and Focus Groups</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2359"><a href="http://geocalendar.agu.org/">AGU GeoCalendar</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2360"><a href="http://about.agu.org/get-social/">Get Social with AGU</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2361"><a href="http://news.agu.org/">AGU Press Releases</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2362"><a href="http://sciencepolicy.agu.org/">Latest Science Policy News</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2363"><a href="http://education.agu.org/">Education and Outreach Programs</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2366"><a href="http://publications.agu.org/eos/"><span><em>Eos</em></span></a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2384"><a href="http://membership.agu.org/aguniverse/"><span><em>AGUniverse</em></span> Newsletter</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2367"><a href="http://sites.agu.org/media-kits/">Media Kit</a></li>
</ul></div></div></article>		   			   </div>

									<div class="small-12 large-4 columns">
									     		     <article id="text-8" class="row widget widget_text"><div class="small-12 columns"><h6><strong>About AGU</strong></h6>   <div class="textwidget">AGU galvanizes a community of Earth and space scientists that collaboratively advances and communicates science and its power to ensure a sustainable future.</div>
											     	      </div></article><article id="text-9" class="row widget widget_text"><div class="small-12 columns"><h6><strong>Get Connected</strong></h6>	 	      <div class="textwidget"><a href="https://www.facebook.com/AmericanGeophysicalUnion" class="share facebook">Facebook</a>
<a href="https://twitter.com/theAGU" class="share twitter">Twitter</a>
<a href="http://www.linkedin.com/groups?homeNewMember=&gid=2196290&trk=" class="share linkedin">Linked In</a>
<a href="http://about.agu.org/get-social/rss-feeds/" class="share rss">RSS Feed</a>
<a href="http://www.youtube.com/user/AGUvideos" class="share youtube">YouTube</a></div>
   						</div></article>		</div>
						</div>

						<div class="row footer-4">
						     <div class="columns small-12">
						     	  		 <article id="text-10" class="row widget widget_text"><div class="small-12 columns">   <div class="textwidget"><p>&copy; 2013. <a href="http://sites.agu.org"/>American Geophysical Union</a> | All rights reserved | <a href="http://about.agu.org/privacy-policy">Privacy Policy</a></p>
<p>2000 Florida Ave. NW, Washington, DC 20009 | Phone: +1 202 462 6900 | Toll Free: 800 966 2481 (North America only) | <a href="mailto:service@agu.org">Customer Service</a> </p>
</div>
		</div></article>		</div>
		</div>
</footer><script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.core.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.widget.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.accordion.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.position.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.menu.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.autocomplete.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.datepicker.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.mouse.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.resizable.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.draggable.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.button.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.dialog.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-content/plugins/agu-netforum/base/js/main.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-content/plugins/agu-netforum/base/js/validations.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-includes/js/jquery/ui/jquery.ui.tooltip.min.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-content/plugins/agu-netforum/templates_1/js/main.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-content/plugins/agu-netforum/templates_1/js/validations.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-content/themes/agu-interim/js/section-close.js'></script>
<script type='text/javascript' src='https://membership.agu.org/wp-content/themes/agu-interim/js/foundation.min.js'></script>

<script>
	(function($) {
		     $(document).foundation();
		     })(jQuery);
</script>

<script type="text/javascript">if(!NREUMQ.f){NREUMQ.f=function(){NREUMQ.push(["load",new Date().getTime()]);var e=document.createElement("script");e.type="text/javascript";e.src=(("http:"===document.location.protocol)?"http:":"https:")+"//"+"js-agent.newrelic.com/nr-100.js";document.body.appendChild(e);if(NREUMQ.a)NREUMQ.a();};NREUMQ.a=window.onload;window.onload=NREUMQ.f;};NREUMQ.push(["nrfj","beacon-6.newrelic.com","fe393d8b28","2827884","YABaZ0VRXUdXBkFdCVlKeVBDWVxaGRVUUwMaA01fWw==",0,222,new Date().getTime(),"","","","",""]);</script></body>
</html>