<article class="row widget widget_nav_menu">
  <div id="abstract-browser-nav" class="columns">
    <h4><strong>Abstract Browser<sub>Beta</sub></strong></h4>
    <ul class="menu"> 
      <li style="padding:3px 0;border-bottom: 1px solid #d5d5d5" class="menu-item"><a href="{{lodspk.home}}">Abstract Browser Home</a></li>
      <li style="padding:3px 0;border-bottom: 1px solid #d5d5d5" class="menu-item"><a href="{{lodspk.home}}meetings">Meetings-at-a-Glance</a></li>
      <li style="padding:3px 0;border-bottom: 1px solid #d5d5d5" class="menu-item"><a href="{{lodspk.home}}sections">AGU Sections</a></li>
      <li style="padding:3px 0;border-bottom: 1px solid #d5d5d5" class="menu-item"><a href="{{lodspk.home}}keywords">Index Terms</a></li>
      <li style="padding:3px 0;border-bottom: 1px solid #d5d5d5" class="menu-item"><a href="{{lodspk.home}}dbsearch.php">Advanced Search</a></li>
    </ul>
  </div>
</article>
